### ISSUE TITLE
GtfsInstance.summarise_weekday performance warnings

### ISSUE THREAD

**Issue by r-leyshon** [datasciencecampus/transport-network-performance#23] opened 2023-07-11 11:30 UTC
**Describe the bug**

GtfsInstance.summarise_weekday() is very slow and raises pandas performance warnings.

**Environment**

 - OS: macos
 - Python version: 3.9.13
 - Java version: openjdk 11.0.19 2023-04-18 LTS

**Steps to reproduce**

1. pytest --runexpensive on branch 15-gtfs-validation-pipeline
2. tests/gtfs/test_validation.py::TestGtfsInstance::test_summarise_weekday_on_pass should PASS
3. Scroll down to warnings summary
4. See warning --> PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

**Expected behavior**

More performant & avoids pd.PerformanceWarning

**Additional context**

Number of warnings on a single use of the function:
tests/gtfs/test_validation.py: 174 warnings

**Comment by SergioRec** [comment] 2023-07-12 09:34
This looks like an issue with `gtfs_kit`, specifically in [`trips.py`](https://github.com/mrcagney/gtfs_kit/blob/master/gtfs_kit/trips.py#L108). Function `compute_trip_activity` is creating a dataframe with one column per date (280 columns in our example) by inserting them one by one with a `for` loop.

**Comment by SergioRec** [comment] 2023-07-12 09:48
Prepared relevant objects with the following:

```
import gtfs_kit as gk
import pandas as pd
from heimdall_transport.gtfs.validation import GtfsInstance

gtfs = GtfsInstance()
available_dates = gtfs.feed.get_dates()
trip_stats = gk.trips.compute_trip_stats(gtfs.feed)
```

Tried compute_trip_activity in isolation using this code:

```
dates = available_dates

f = gtfs.feed.trips.copy()
for date in dates:
    f[date] = f["trip_id"].map(
        lambda trip_id: int(gtfs.feed.is_active_trip(trip_id, date))
    )
f
```
Runs in ~9.5 s with warnings.

Modifying it with proposed solution for the warning (using `pd.concat`):

```
dates = available_dates

f = gtfs.feed.trips.copy()
for date in dates:
    a = f["trip_id"].map(
        lambda trip_id: int(gtfs.feed.is_active_trip(trip_id, date))
    )
    f = pd.concat([f, a.rename(date)], axis=1)
f
```
Runs in ~9.5 s without warnings.

I'd say the slow speed is caused by the `for` loop and not the dataframe fragmentation.

**Comment by SergioRec** [comment] 2023-07-12 09:58
Also note that original code only starts producing warnings if `len(available_dates) > 97`.

**Comment by r-leyshon** [comment] 2023-07-27 09:21
@CBROWN-ONS Sorry they're not prettier, but hopefully helpful. logs attached.
You can see summarise_weekday() takes 12 seconds for the Newport fixture, which is most of the time taken to run the pipeline. As the table output is trunctated, I've attached a csv with the table too.

[piplog.txt](https://github.com/datasciencecampus/transport-network-performance/files/12181525/piplog.txt)


[newport-weekday-stats.csv](https://github.com/datasciencecampus/transport-network-performance/files/12181511/newport-weekday-stats.csv)

**Comment by ethan-moss** [comment] 2023-08-10 08:11
Closing issue, since fix has been merged into `15-gtfs-validation` branch.

**Closed as completed by ethan-moss** 2023-08-10 08:11 UTC
Labels: medium, won't
