### ISSUE TITLE
standardise defensive checks in GTFS module

### ISSUE THREAD

**Issue by r-leyshon** [datasciencecampus/transport-network-performance#157] opened 2023-09-29 10:33 UTC
**Description of the Feature to be Added**

GTFS module needs to be brought up to speed with changes in utils.defence. Standardising the use of these utilities and removing some duplicated type checks, associated refactoring of tests will be needed.

**(OPTIONAL) Suggested Implementations**

**Additional context**

**Comment by ethan-moss** [comment] 2023-10-09 13:10
Duplicate of #152, so closing.

**Closed as not planned by ethan-moss** 2023-10-09 13:10 UTC
Labels: needs triage
